alias tmux="tmux attach || tmux -f ~/.tmux.conf"
alias t=tmux
alias gti=git
alias gt=git
alias gs="git status"
alias gl="tig"
alias lg=gl
alias vi='/Applications/MacVim.app/Contents/MacOS/Vim "$@"'
alias iv=vi
alias v=vi
alias l=ls
